# Generated by Django 2.0 on 2017-12-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0002_appcasestep_apptestdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcase',
            options={'verbose_name': 'app测试用例', 'verbose_name_plural': 'app测试用例'},
        ),
    ]
