# Generated by Django 2.0 on 2017-12-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20171230_1157'),
        ('apptest', '0004_auto_20171230_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcase',
            options={'verbose_name': 'app测试用例', 'verbose_name_plural': 'app测试用例'},
        ),
        migrations.AddField(
            model_name='appcase',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
