# Generated by Django 2.0 on 2018-01-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0005_auto_20171230_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcasestep',
            name='appcasename',
        ),
    ]
