# Generated by Django 2.0 on 2018-01-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0006_remove_appcasestep_appcasename'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcase',
            name='Appcasestep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apptest.Appcasestep'),
        ),
    ]
