# Generated by Django 2.0 on 2018-01-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0007_appcase_appcasestep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcase',
            name='Appcasestep',
        ),
    ]
