# Generated by Django 2.0 on 2017-12-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171226_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品管理', 'verbose_name_plural': '产品管理'},
        ),
    ]
