# Generated by Django 2.0 on 2017-12-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20171230_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品管理', 'verbose_name_plural': '产品管理'},
        ),
    ]
