# Generated by Django 2.0 on 2018-01-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20171230_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producter',
            field=models.CharField(max_length=200, null=True, verbose_name='产品负责人'),
        ),
    ]
