# Generated by Django 2.0 on 2017-12-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_webcasestep_webtestdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webcase',
            options={'verbose_name': 'web测试用例', 'verbose_name_plural': 'web测试用例'},
        ),
    ]
