# Generated by Django 2.0 on 2017-12-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0003_auto_20171226_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webcase',
            options={},
        ),
    ]
