# Generated by Django 2.0.1 on 2018-01-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0005_auto_20171230_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcasestep',
            name='webcasename',
        ),
    ]
