# Generated by Django 2.0 on 2017-12-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='apitester',
            field=models.CharField(max_length=16, verbose_name='测试负责人'),
        ),
    ]
