# Generated by Django 2.0 on 2017-12-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20171226_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apis',
            options={'verbose_name': '单一场景接口', 'verbose_name_plural': '单一场景接口'},
        ),
        migrations.AlterModelOptions(
            name='apitest',
            options={'verbose_name': '流程场景接口', 'verbose_name_plural': '流程场景接口'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '接口产品管理', 'verbose_name_plural': '接口产品管理'},
        ),
    ]
