# Generated by Django 2.0 on 2017-12-26 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20171226_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
