# Generated by Django 2.0 on 2017-12-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20171230_1054'),
        ('apitest', '0007_auto_20171226_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
