# Generated by Django 2.0 on 2017-12-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_apis_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apitest',
            options={},
        ),
    ]
