# Generated by Django 2.0 on 2017-12-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20171230_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apis',
            options={'verbose_name': '单一场景接口', 'verbose_name_plural': '单一场景接口'},
        ),
        migrations.AlterModelOptions(
            name='apitest',
            options={'verbose_name': '流程场景接口', 'verbose_name_plural': '流程场景接口'},
        ),
        migrations.AddField(
            model_name='apitest',
            name='apitestdesc',
            field=models.CharField(max_length=64, null=True, verbose_name='描述'),
        ),
    ]
