# Generated by Django 2.0 on 2018-01-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0010_auto_20171230_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistep',
            name='apistep',
            field=models.CharField(max_length=100, null=True, verbose_name='测试步聚'),
        ),
    ]
