# Generated by Django 2.0 on 2018-01-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0011_apistep_apistep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apimethod',
            field=models.CharField(max_length=200, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='apiparamvalue',
            field=models.CharField(max_length=800, verbose_name='请求参数和值'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apimethod',
            field=models.CharField(choices=[('0', 'get'), ('1', 'post')], default='0', max_length=200, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiparamvalue',
            field=models.CharField(max_length=800, verbose_name='请求参数和值'),
        ),
    ]
