# Generated by Django 2.0.1 on 2018-01-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0014_auto_20180128_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='apiresponse',
            field=models.CharField(max_length=800, null=True, verbose_name='响应数据'),
        ),
        migrations.AddField(
            model_name='apistep',
            name='apiresponse',
            field=models.CharField(max_length=800, null=True, verbose_name='响应数据'),
        ),
    ]
