# Generated by Django 2.0.1 on 2018-01-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0015_auto_20180129_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apiresponse',
            field=models.CharField(max_length=5000, null=True, verbose_name='响应数据'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiresponse',
            field=models.CharField(max_length=5000, null=True, verbose_name='响应数据'),
        ),
    ]
