# Generated by Django 2.0 on 2018-01-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bugdetail',
            field=models.CharField(max_length=2000, verbose_name='bug详情'),
        ),
    ]
